version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  data:
    image: hasura/graphql-engine:v2.0.3.cli-migrations-v3
    volumes:
      - ./services/data/migrations:/hasura-migrations
      - ./services/data/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"

  api:
    build: ./services/api
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}

  web:
    build: ./services/web
    ports:
      - "3000:3000"
    restart: always
    environment:
      API_HOST: ${API_HOST}

volumes:
  db_data:
