FROM node:current-alpine

# Create app directory
WORKDIR /app

RUN npm config set unsafe-perm true 
COPY package.json package-lock.json tsconfig.json nodemon.json .eslintrc ./
RUN npm i -g nodemon typescript @types/node eslint ts-node
RUN npm i

EXPOSE 9000

CMD ["nodemon"]